#!/bin/sh
OPTIONS=
FILES=
for ARG
do
  case "$ARG" in
    -*) OPTIONS="$OPTIONS $ARG";;
    *) ARG="`expr $ARG : '\(.*\.MW\)' '|' $ARG.MW`"
       FILES="$FILES $ARG";;
  esac
done
if test -z "$FILES"
then
  echo 'mwcat: fatal: must specify filenames; use unsqueeze for a filter' 1>&2
  exit 1
fi
set $FILES
for ARG
do
  unsqueeze $OPTIONS < "$ARG"
done
exit 0
